### ISSUE TITLE
能否支持以守护进程运行？

### ISSUE THREAD

**Issue by qiufeihai** [dengsgo/fileboy#12]
能否支持以守护进程运行？开机自启动

**Comment by dengsgo** [comment]
`fileboy` 本身不支持守护进程模式。linux 环境可以使用 `screen` 、`systemd` 这些工具实现守护进程和开机自启。

**Comment by dengsgo** [comment]
[v1.15](https://github.com/dengsgo/fileboy/releases/tag/v1.15) 版本已经支持 deamon 模式。
