### ISSUE TITLE
go get 出现错误

### ISSUE THREAD

**Issue by luotianzhu** [dengsgo/fileboy#13]
go get: github.com/dengsgo/fileboy@v0.0.0-20200308052638-c0364a62bc89: parsing go.mod:
        module declares its path as: fileboy
                but was required as: github.com/dengsgo/fileboy

**Comment by dengsgo** [comment]
这个 repo 不是一个库，不能被 import. 

尝试执行下面的命令来编译：
```bash
git clone https://github.com/dengsgo/fileboy.git
cd fileboy
export GO111MODULE=on  
go env -w GOPROXY=https://goproxy.io,direct
go get -u 
go build
./fileboy
```
