### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by MoChKa** [dengsgo/fileboy#14]
环境：`Linux Manjaro64位`
下载了 `Linux` 版本的可执行文件后，将文件所在目录添加至环境变量，执行 `fileboy` 时出现提示权限不够
```powershell
$ fileboy init
zsh: 权限不够: fileboy

**Comment by dengsgo** [comment]
执行 `chmod +x fileboy` 给 fileboy 赋予可执行权限

**Comment by MoChKa** [comment]
多谢，忘记了这个步骤.
