### ISSUE TITLE
变量占位符 {{file}} bug

### ISSUE THREAD

**Issue by q629988171** [dengsgo/fileboy#16]
环境：
Windows 7 SP1 专业版

filegirl 配置
command:exec:- cmd.exe /c echo {{file}} {{ext}} {{event}}

描述：
event create : "D:\test\1\新建文本文档.txt"
EXEC [cmd.exe /c echo 1  write]

正确情况应该显示：echo 1/新建文本文档.txt

复现过程：

打开 D:\test\1\

右键->新建->文本文档

**Comment by dengsgo** [comment]
应该是延迟执行的问题，可以贴一下详细的 filegirl 配置

**Comment by q629988171** [comment]
> 应该是延迟执行的问题，可以贴一下详细的 filegirl 配置

core:
    version: 1
monitor:
    includeDirs:
        - .,*
    exceptDirs:
        - .idea
        - .git
        - .vscode
        - node_modules
        - vendor
    types:
        - .*
    events:
        - write
        - rename
        - remove
        - create
        - chmod
command:
    exec:
        - cmd.exe /c echo {{file}} {{ext}} {{event}}
    delayMillSecond: 10000
notifier:
    callUrl: ""
instruction:
    - ignore-warn

**Comment by dengsgo** [comment]
延迟执行是为了解决短时间内重复执行命令的问题，所以只会保留最后一次触发的事件。你可以将 delayMillSecond 设置为 0，看下输出是否会遗漏 {{file}} 变量

```yaml
delayMillSecond: 0
```
