### ISSUE TITLE
[建议意见]通知器在命令执行完成后会发送 http 请求 ?

### ISSUE THREAD

**Issue by q629988171** [dengsgo/fileboy#17]
注意：标题字数有限无法说明详细内容
说明：

要是早点发现 fileboy就好（就不用重复造轮子），我用python写了类似的。

监控文件变更，然后执行定义的命令，文件变更后命令在60秒后才会执行，如果60秒内有新事件产生就重新开始计时。

使用场景：自动打包编译（文件夹更新后，自动 Inno setup Compile）

通知器，还没写，计划用微信推送，实现想法和你一样。

特殊指令没有想过要实现。

问题一：

通知器在什么时候会发送 http 请求 ?

是否支持，命令执行完成后，根据命令执行 exit code(非 fileboy) 通知结果。

问题二：

    #   should-finish     （1）触发执行 'exec' 时(C)，如果上一次的命令(L)未退出（还在执行），会等待 L 退出（而不是强制 kill ），直到 L 有明确 exit code 才会开始执行本次命令。
    #                     （2）在等待 L 退出时，又有新事件触发了命令执行(N)，则 C 执行取消，只会保留最后一次的 N 执行

（1）我明白，（2）这样的设计不是和（1）冲突吗？理由：（1）等待，（2）取消。

问题来了：should-finish 到底是等待还是取消？

问题三：

由于 fileboy 无法预估命令执行的时长，为防止执行中的命令一直阻塞，导致后续的命令任务响应滞后，现在采用的策略是有新任务进来就直接中断之前的任务（而不管它是否还在执行）。

中断之前的任务是 kill，还是忽略（看来是忽略）

问题四：
所有配置默认，除以下时间增加为10秒

delayMillSecond: 10000

需求：假设我有一个文件夹，里面有 A,B,C 三个文件夹，需要监控，并且通过 inno setup 进行打包成3个 setup.exe

1秒后，A文件夹更新，开始打包成 A_setup.exe

2秒后，B文件夹更新，开始打包成 B_setup.exe

3秒后，C文件夹更新，开始打包成 C_setup.exe

命令只会执行，开始打包成 C_setup.exe。A和B文件夹的更新会被忽略，没有打包。

解决思路：

- 加入队列
- 运行3个fileboy，分别监控 A,B,C文件夹

**Comment by dengsgo** [comment]
> 问题一：
> 
> 通知器在什么时候会发送 http 请求 ?
> 
> 是否支持，命令执行完成后，根据命令执行 exit code(非 fileboy) 通知结果。

网络通知器通知的时机目前是和执行自定义命令相同的。如果有需要监听执行结束的这个需求，建议是将自定义命令写在一个 shell 脚本里，在脚本最后写自己的业务逻辑，然后在 `fileboy` 的自定义命令中配置执行这个脚本就行了。

> 问题二：
> 
> ```
> #   should-finish     （1）触发执行 'exec' 时(C)，如果上一次的命令(L)未退出（还在执行），会等待 L 退出（而不是强制 kill ），直到 L 有明确 exit code 才会开始执行本次命令。
> #                     （2）在等待 L 退出时，又有新事件触发了命令执行(N)，则 C 执行取消，只会保留最后一次的 N 执行
> ```
> 
> （1）我明白，（2）这样的设计不是和（1）冲突吗？理由：（1）等待，（2）取消。
> 
> 问题来了：should-finish 到底是等待还是取消？

`should-finish` 是等待，直到前面的命令执行完退出了才会接着执行后面触发的命令。2 的意思是在等待前面的命令执行完之前，有文件频繁更新事件导致堆积了很多未执行任务的话，那么只会保留最后一个任务，这最后一个任务也会等到前面执行命令执行完才会执行。

> 问题三：
> 
> 由于 fileboy 无法预估命令执行的时长，为防止执行中的命令一直阻塞，导致后续的命令任务响应滞后，现在采用的策略是有新任务进来就直接中断之前的任务（而不管它是否还在执行）。
> 
> 中断之前的任务是 kill，还是忽略（看来是忽略）

如果没有配置`should-finish`, 会强制中断前面的命令（kill）.


> 问题四：
> 所有配置默认，除以下时间增加为10秒
> 
> delayMillSecond: 10000
> 
> 需求：假设我有一个文件夹，里面有 A,B,C 三个文件夹，需要监控，并且通过 inno setup 进行打包成3个 setup.exe
> 
> 1秒后，A文件夹更新，开始打包成 A_setup.exe
> 
> 2秒后，B文件夹更新，开始打包成 B_setup.exe
> 
> 3秒后，C文件夹更新，开始打包成 C_setup.exe
> 
> 命令只会执行，开始打包成 C_setup.exe。A和B文件夹的更新会被忽略，没有打包。
> 
> 解决思路：
> 
> * 加入队列
> * 运行3个fileboy，分别监控 A,B,C文件夹

这个还是建议通过写shell脚本的方式来处理，配置 fileboy 执行这个脚本。

**Comment by q629988171** [comment]
@dengsgo 

问题四，shell 脚本无法处理这种业务场景。

理由：
fileboy 虽然会记录A,B,C文件夹更新，但只会执行最后一个变更事件。

SHELL脚本，需要外部输入才知道要处理哪一个文件夹。

结果就是只能处理C文件夹。无法对所有更新的文件夹进行处理。

**Comment by dengsgo** [comment]
#18 TODO
