### ISSUE TITLE
[建议]增加指定配置文件启动

### ISSUE THREAD

**Issue by q629988171** [dengsgo/fileboy#18]
比如：nginx -c 配置文件
场景：多配置启动。
当前：如果我要作用多配置启动，需要复制2个 fileboy进程和两个配置文件，放在不同位置，很是繁琐。

**Comment by q629988171** [comment]
@dengsgo 更新来了：https://github.com/q629988171/fileboy/commit/d195046696c8937b802e2a1298be331d45083505

**Comment by dengsgo** [comment]
> @dengsgo 更新来了：[q629988171@d195046](https://github.com/q629988171/fileboy/commit/d195046696c8937b802e2a1298be331d45083505)

增加该功能需要考虑以下几点：

- fileboy 项目根路径。这个会影响配置在 `command -> exec ` 中相对路径命令的查找和执行（现在是以`filegirl.yaml`为项目根）；
- `fileboy init` 初始化指定路径的 yaml 配置；
- 如何设计命令。减少用户的理解成本；
- 异常情况处理；
- 使用文档。

**Comment by dengsgo** [comment]
> 当前：如果我要作用多配置启动，需要复制2个 fileboy进程和两个配置文件，放在不同位置，很是繁琐。

可以把 `fileboy` 放到 PATH 中，不用复制多个。

**Comment by q629988171** [comment]
> > 当前：如果我要作用多配置启动，需要复制2个 fileboy进程和两个配置文件，放在不同位置，很是繁琐。
> 
> 可以把 `fileboy` 放到 PATH 中，不用复制多个。

新的功能会带来新的问题。这个方法好，这样就可以解决多配置的问题，又不需要更新代码，也不会带来新的问题。

**Comment by congqianzm** [comment]
请问下”指定启动时的配置文件路径“这个功能会考虑加进去吗

**Comment by dengsgo** [comment]
> 请问下”指定启动时的配置文件路径“这个功能会考虑加进去吗

近期会释放新版本增加该功能，可以多关注一下

**Comment by congqianzm** [comment]
> > 请问下”指定启动时的配置文件路径“这个功能会考虑加进去吗
> 
> 近期会释放新版本增加该功能，可以多关注一下

新版本功能也包含"init时指定filegirl文件路径"吗，本地命令行工具想调用fileboy直接集成监控功能，但是又不能对本地项目产生侵入影响

**Comment by dengsgo** [comment]
> > > 请问下”指定启动时的配置文件路径“这个功能会考虑加进去吗
> > 
> > 
> > 近期会释放新版本增加该功能，可以多关注一下
> 
> 新版本功能也包含"init时指定filegirl文件路径"吗，本地命令行工具想调用fileboy直接集成监控功能，但是又不能对本地项目产生侵入影响

`init` 生成的配置文件内容是固定的，考虑到一般需要用户修改成适合自己的项目后使用，所以新版尚未集成这个功能。
