### ISSUE TITLE
How can I correctly configure the python command in the filegirl.yaml file

### ISSUE THREAD

**Issue by wnark** [dengsgo/fileboy#22]
Hello, I currently only know python3+shell. How do the commands inside execute python commands? Is there a filegirl.yaml reference that can run through?
My python command is to generate a torrent of files larger than 100M in the folder and save it in another folder. And I found your command in the readme is golang.

**Comment by wnark** [comment]
It would be great if you can use a common file hot reload project written in python, but the results I searched for so far show that only your project is a common file hot reload

**Comment by dengsgo** [comment]
`fileboy` is written in go, but as a tool, it is applicable to any programming language project, and python is no exception. You can flexibly configure the 'command - > exec' configuration item in filegirl.yaml. Typical are as follows, I guess:

```yaml
command:
  exec:
    - python3 xxxx.py
```

Simply put, the configuration item can fill in the commands you manually enter in the shell. Hope to help you.
