### ISSUE TITLE
需要支持程序【根】和【绝对】路径的支持

### ISSUE THREAD

**Issue by 456vv** [dengsgo/fileboy#25]
微软的绝对路径是 C:\a\b\c，D:\a\b\c。linux绝对路径是/a/b/c。

1，```C:\ABC>>fileboy --filegirl C:/Datas/filegirl.yaml``` 结果路径变成:```C:\ABC\C:/Datas/filegirl.yaml```

2，程序启动目录不能指定，必须进到监听目录执行fileboy。

**Comment by dengsgo** [comment]
感谢反馈。
> 1，`C:\ABC>>fileboy --filegirl C:/Datas/filegirl.yaml` 结果路径变成:`C:\ABC\C:/Datas/filegirl.yaml`
  
已修复此问题，请重新下载[2022.5.4编译版本](https://github.com/dengsgo/fileboy/releases/tag/v1.16)或者 pull master 代码自行编译。

> 
> 2，程序启动目录不能指定，必须进到监听目录执行fileboy。

`fileboy` 有工作区，程序启动所在的路径默认是当前进程的工作区，无法监听除工作区以外的路径、目录。
