### ISSUE TITLE
支持优雅的重启吗?

### ISSUE THREAD

**Issue by wujunze** [dengsgo/fileboy#5]
支持优雅的重启吗?

不停服务的重启  类似于`nginx reload` 这样

**Comment by dengsgo** [comment]
不支持的。  
能描述一下你的使用场景吗？

**Comment by wujunze** [comment]
类似于nginx reload 这样  不停服的重启

**Comment by dengsgo** [comment]
`fileboy`本身是不支持优雅重启的，也就是说进程启动后`filegirl.yaml`配置变更也不会自动重载，如需加载新配置需要杀掉进程重新启动`fileboy`。  
如果只是使用`fileboy`去运行命令重启其他的进程，这个要看那个进程是不是支持优雅重启，比如`nginx`就可以配置`command -> exec` `nginx reload`来优雅重启`nginx`
