### ISSUE TITLE
command not found: fileboy

### ISSUE THREAD

**Issue by felix0324324** [dengsgo/fileboy#9]
問題1 : 我在Mac機的Terminal下 fileboy init  
出了 command not found: fileboy

問題2 :
下载已经编译好的对应平台二进制文件，
重命名为fileboy，加入系统 Path 中即可。
系统 Path 是指那裡？？

謝謝啊

**Comment by dengsgo** [comment]
> 問題1 : 我在Mac機的Terminal下 fileboy init
> 出了 command not found: fileboy
> 
> 問題2 :
> 下载已经编译好的对应平台二进制文件，
> 重命名为fileboy，加入系统 Path 中即可。
> 系统 Path 是指那裡？？
> 
> 謝謝啊

系统 path 是指系统的 `PATH` 变量，你需要把 `fileboy` 所在的路径加入到 `PATH` 中才能在命令行 shell 中使用. 具体设置可以 google 一下 “mac path 设置” 关键字。
